PUT http://<HOSTPORT><PATH> HTTP/1.1
Host: <HOST>:<PORT>
Authorization: Digest username="<USER>", realm="<REALM>", uri="http://<HOSTPORT><PATH>", qop=auth, nonce="<NONCE>", nc=<NC>, cnonce="<CNONCE>", response="<RESPONSE>"
Connection: close
Content-Type: text/plain
Content-Length: 65

here comes a PUT method

in text/plain format

hooray for PUT!!!
