HEAD http://<HOSTPORT><PATH><SUFFIX1> HTTP/1.1
Range: bytes=-100
Host: <HOST>:<PORT>
<PIPELINE>
HEAD http://<HOSTPORT><PATH> HTTP/1.1
Negotiate: 1.0
Host: <HOST>:<PORT>
<PIPELINE>
HEAD http://<HOSTPORT><PATH><SUFFIX2> HTTP/1.1
Host: <HOST>:<PORT>
Connection: close

